service: BacklogCountTool

provider:
  name: aws
  runtime: python3.6
  region: ap-northeast-1

plugins:
  - serverless-python-requirements

functions:
  backlog:
    handler: BacklogCountTool.lambda_handler